site_name: UL HPC Tutorials
pages:
- ['index.md', 'Home']
- ['basic/getting_started/README.md', 'Basic Tutorials', 'Getting Started']
- ['basic/sequential_jobs/README.md', 'Basic Tutorials', 'HPC workflow with sequential jobs']
- ['advanced/RESIF/README.md',     'Advanced Software Management', 'RESIF']
- ['advanced/EasyBuild/README.md', 'Advanced Software Management', 'Easybuild']
- ['advanced/OSU_MicroBenchmarks/README.md', 'MPI', 'The OSU Micro-benchmarks']
- ['advanced/HPL/README.md',                 'MPI', 'High Performance Linpack (HPL)']
- ['advanced/MATLAB1/README.md', 'Mathematics', 'MATLAB1']
- ['advanced/R/README.md',      'Mathematics', 'R - statistical computing ']
- ['advanced/Bioinformatics/README.md',         'Bio-informatic', 'Running bioinformatics software']
- ['advanced/Galaxy/README.md', 'Bio-informatic', 'Galaxy']
- ['advanced/Allinea/README.md',   'Parallel Debuggers', 'Allinea']
- ['advanced/TotalView/README.md', 'Parallel Debuggers', 'TotalView']
- ['advanced/Vagrant/README.md', 'Virtualization', 'Vagrant']
- ['advanced/vm5k/README.md', 'Virtualization', 'Grid5000: Automatic VM deployment with VM5K']
- ['advanced/ParallelExec/README.md', 'Parallel execution', 'Running parallel software']
- ['contributing.md', 'Documentation', 'Contributing']
- ['rtfd.md', 'Documentation', 'RTFD']
- ['contacts.md', 'Contacts']
theme: readthedocs
